// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/contactbook.proto

package com.mycontacts.app.contactbook.model;

public final class ContractBookProto {
  private ContractBookProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.Contact)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code model.Contact}
   */
  public  static final class Contact extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.Contact)
      ContactOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contact() {
      id_ = 0;
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contact(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_Contact_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycontacts.app.contactbook.model.ContractBookProto.Contact.class, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycontacts.app.contactbook.model.ContractBookProto.Contact)) {
        return super.equals(obj);
      }
      com.mycontacts.app.contactbook.model.ContractBookProto.Contact other = (com.mycontacts.app.contactbook.model.ContractBookProto.Contact) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycontacts.app.contactbook.model.ContractBookProto.Contact prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.Contact)
        com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_Contact_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycontacts.app.contactbook.model.ContractBookProto.Contact.class, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder.class);
      }

      // Construct using com.mycontacts.app.contactbook.model.ContractBookProto.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_Contact_descriptor;
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact getDefaultInstanceForType() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.Contact.getDefaultInstance();
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact build() {
        com.mycontacts.app.contactbook.model.ContractBookProto.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact buildPartial() {
        com.mycontacts.app.contactbook.model.ContractBookProto.Contact result = new com.mycontacts.app.contactbook.model.ContractBookProto.Contact(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycontacts.app.contactbook.model.ContractBookProto.Contact) {
          return mergeFrom((com.mycontacts.app.contactbook.model.ContractBookProto.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycontacts.app.contactbook.model.ContractBookProto.Contact other) {
        if (other == com.mycontacts.app.contactbook.model.ContractBookProto.Contact.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycontacts.app.contactbook.model.ContractBookProto.Contact parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycontacts.app.contactbook.model.ContractBookProto.Contact) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.Contact)
    }

    // @@protoc_insertion_point(class_scope:model.Contact)
    private static final com.mycontacts.app.contactbook.model.ContractBookProto.Contact DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycontacts.app.contactbook.model.ContractBookProto.Contact();
    }

    public static com.mycontacts.app.contactbook.model.ContractBookProto.Contact getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact>
        PARSER = new com.google.protobuf.AbstractParser<Contact>() {
      @java.lang.Override
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contact(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contact> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mycontacts.app.contactbook.model.ContractBookProto.Contact getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:model.ContactBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact> 
        getContactList();
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    com.mycontacts.app.contactbook.model.ContractBookProto.Contact getContact(int index);
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    int getContactCount();
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    java.util.List<? extends com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder> 
        getContactOrBuilderList();
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder getContactOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code model.ContactBook}
   */
  public  static final class ContactBook extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:model.ContactBook)
      ContactBookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactBook.newBuilder() to construct.
    private ContactBook(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactBook() {
      contact_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                contact_ = new java.util.ArrayList<com.mycontacts.app.contactbook.model.ContractBookProto.Contact>();
                mutable_bitField0_ |= 0x00000001;
              }
              contact_.add(
                  input.readMessage(com.mycontacts.app.contactbook.model.ContractBookProto.Contact.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          contact_ = java.util.Collections.unmodifiableList(contact_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_ContactBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_ContactBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.class, com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.Builder.class);
    }

    public static final int CONTACT_FIELD_NUMBER = 1;
    private java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact> contact_;
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    public java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact> getContactList() {
      return contact_;
    }
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    public java.util.List<? extends com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder> 
        getContactOrBuilderList() {
      return contact_;
    }
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    public int getContactCount() {
      return contact_.size();
    }
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    public com.mycontacts.app.contactbook.model.ContractBookProto.Contact getContact(int index) {
      return contact_.get(index);
    }
    /**
     * <code>repeated .model.Contact contact = 1;</code>
     */
    public com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder getContactOrBuilder(
        int index) {
      return contact_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contact_.size(); i++) {
        output.writeMessage(1, contact_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contact_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contact_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook)) {
        return super.equals(obj);
      }
      com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook other = (com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook) obj;

      boolean result = true;
      result = result && getContactList()
          .equals(other.getContactList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactCount() > 0) {
        hash = (37 * hash) + CONTACT_FIELD_NUMBER;
        hash = (53 * hash) + getContactList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code model.ContactBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:model.ContactBook)
        com.mycontacts.app.contactbook.model.ContractBookProto.ContactBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_ContactBook_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_ContactBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.class, com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.Builder.class);
      }

      // Construct using com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContactFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.internal_static_model_ContactBook_descriptor;
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook getDefaultInstanceForType() {
        return com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.getDefaultInstance();
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook build() {
        com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook buildPartial() {
        com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook result = new com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook(this);
        int from_bitField0_ = bitField0_;
        if (contactBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            contact_ = java.util.Collections.unmodifiableList(contact_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contact_ = contact_;
        } else {
          result.contact_ = contactBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook) {
          return mergeFrom((com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook other) {
        if (other == com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook.getDefaultInstance()) return this;
        if (contactBuilder_ == null) {
          if (!other.contact_.isEmpty()) {
            if (contact_.isEmpty()) {
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactIsMutable();
              contact_.addAll(other.contact_);
            }
            onChanged();
          }
        } else {
          if (!other.contact_.isEmpty()) {
            if (contactBuilder_.isEmpty()) {
              contactBuilder_.dispose();
              contactBuilder_ = null;
              contact_ = other.contact_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactFieldBuilder() : null;
            } else {
              contactBuilder_.addAllMessages(other.contact_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact> contact_ =
        java.util.Collections.emptyList();
      private void ensureContactIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          contact_ = new java.util.ArrayList<com.mycontacts.app.contactbook.model.ContractBookProto.Contact>(contact_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mycontacts.app.contactbook.model.ContractBookProto.Contact, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder, com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder> contactBuilder_;

      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact> getContactList() {
        if (contactBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contact_);
        } else {
          return contactBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public int getContactCount() {
        if (contactBuilder_ == null) {
          return contact_.size();
        } else {
          return contactBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact getContact(int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);
        } else {
          return contactBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder setContact(
          int index, com.mycontacts.app.contactbook.model.ContractBookProto.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.set(index, value);
          onChanged();
        } else {
          contactBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder setContact(
          int index, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder addContact(com.mycontacts.app.contactbook.model.ContractBookProto.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(value);
          onChanged();
        } else {
          contactBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder addContact(
          int index, com.mycontacts.app.contactbook.model.ContractBookProto.Contact value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactIsMutable();
          contact_.add(index, value);
          onChanged();
        } else {
          contactBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder addContact(
          com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder addContact(
          int index, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder builderForValue) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder addAllContact(
          java.lang.Iterable<? extends com.mycontacts.app.contactbook.model.ContractBookProto.Contact> values) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contact_);
          onChanged();
        } else {
          contactBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public Builder removeContact(int index) {
        if (contactBuilder_ == null) {
          ensureContactIsMutable();
          contact_.remove(index);
          onChanged();
        } else {
          contactBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder getContactBuilder(
          int index) {
        return getContactFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder getContactOrBuilder(
          int index) {
        if (contactBuilder_ == null) {
          return contact_.get(index);  } else {
          return contactBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public java.util.List<? extends com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder> 
           getContactOrBuilderList() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contact_);
        }
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder addContactBuilder() {
        return getContactFieldBuilder().addBuilder(
            com.mycontacts.app.contactbook.model.ContractBookProto.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder addContactBuilder(
          int index) {
        return getContactFieldBuilder().addBuilder(
            index, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .model.Contact contact = 1;</code>
       */
      public java.util.List<com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder> 
           getContactBuilderList() {
        return getContactFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mycontacts.app.contactbook.model.ContractBookProto.Contact, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder, com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mycontacts.app.contactbook.model.ContractBookProto.Contact, com.mycontacts.app.contactbook.model.ContractBookProto.Contact.Builder, com.mycontacts.app.contactbook.model.ContractBookProto.ContactOrBuilder>(
                  contact_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:model.ContactBook)
    }

    // @@protoc_insertion_point(class_scope:model.ContactBook)
    private static final com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook();
    }

    public static com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactBook>
        PARSER = new com.google.protobuf.AbstractParser<ContactBook>() {
      @java.lang.Override
      public ContactBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactBook(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactBook> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactBook> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mycontacts.app.contactbook.model.ContractBookProto.ContactBook getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_Contact_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_Contact_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_ContactBook_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_ContactBook_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033resources/contactbook.proto\022\005model\"#\n\007" +
      "Contact\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\".\n\013Con" +
      "tactBook\022\037\n\007contact\030\001 \003(\0132\016.model.Contac" +
      "tB9\n$com.mycontacts.app.contactbook.mode" +
      "lB\021ContractBookProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_model_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_Contact_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_model_ContactBook_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_ContactBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_ContactBook_descriptor,
        new java.lang.String[] { "Contact", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
